### PR TITLE
JEP 386 patch - minor cleanup

### PR DESCRIPTION
**Pull request by AlexanderScherbatiy**
"JEP 386 patch - minor cleanup" changes discussed on portola-dev alias:
https://mail.openjdk.java.net/pipermail/portola-dev/2020-August/000471.html

Changed:
* RELEASE_FILE_OS_LIBC is introduced in make files
* glibc_version is renamed to libc_version
* added fix for numa_node_to_cpus NUMA method
* WhiteBox is used to check musl libc in tests
* Platform.isBusybox(tool) method is added to check busybox in tests 

Removed:
* HOTSPOT_TARGET_LIBC flag
* workaround for issues for execvp file call in childproc.c file
* workaround for coredump issue in ps_core.c file

Skipped:
* isnanf change from globalDefinitions_gcc.hpp
* SIGRTMAX changes from NativeThread.c and linux_close.c files

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Download
`$ git fetch https://git.openjdk.java.net/portola pull/12/head:pull/12`
`$ git checkout pull/12`

### CODE REVIEW

**Comment by vidmik** [comment]
This all looks good. I'm trying to decide whether I should pull in jdk-16+13 before integrating this, so that we get the upstream fixes for isnanf and WAKEUP_SIGNAL first. Worst case that would mean you'd have to resolve conflicts, but it should be fairly straightforward. Thoughts?

**Comment by AlexanderScherbatiy** [comment]
Yes, let's integrate upstream fixes first and I will update the pull request with resolved confilicts.

**Comment by vidmik** [comment]
I see that those fixes are not yet in a promoted build, so will have to wait until jdk-16+14.

**Comment by AlexanderScherbatiy** [comment]
The pull request is updated according to changes in the pull request to jdk: https://github.com/openjdk/jdk/pull/49

**Comment by vidmik** [comment]
Do you want to wait for the upstream PR to stabilize or should I merge this PR as-is? I'm flexible.

**Comment by AlexanderScherbatiy** [comment]
Merging the PR now is better for me because it avoids future conflict resolutions.

**Comment by vidmik** [comment]
Please add a /integrate comment and I'll issue the /sponsor command.

**Pull request closed without merging**
